// mapped by question number and output data
export const OutputData = {
  1: ['0 1 2 3 6', '4 5 6 7 22', '8 9 10 11 38'],
  2: ['92 93 94 = 279', '85 66 86 88 = 325'],
  3: [
    'Original string: The quick brown fox jumps over the lazy dog.',
    "position of the word 'fox': 4",
    "position of the word 'the': 7",
    "position of the word 'lazy': 8",
  ],
  4: ['The total number of words: 10', 'The number of character: 56'],
  5: [
    'Number of alphabets: 14',
    'Number of digits: 0',
    'Number of special Characters: 7',
  ],
  6: ['Number of vowels: 3', 'Number of consonant: 7'],
  7: [
    'Enter the number of rows (m): 2',
    'Enter the number of columns (n): 2',
    'Enter the elements of the first matrix:',
    'Element [0, 0]: 1',
    'Element [0, 1]: 2',
    'Element [1, 0]: 3',
    'Element [1, 1]: 4',
    'Enter the elements of the second matrix:',
    'Element [0, 0]: 5',
    'Element [0, 1]: 6',
    'Element [1, 0]: 7',
    'Element [1, 1]: 8',
    'The resulting matrix after addition is:',
    '6 8',
    '',
    '10 12',
  ],
  8: ['Area of Rectangle: 200'],
  12: ['9', '20'],
  13: ['Event Initiate'],
  14: [
    'Accessing element at index 5',
    'Index was outside the bounds of the array.',
  ],
  15: [
    'Enter a positive number: 20',
    'The value 20 is valid',
    'Execution finished.',
  ],
  16: [
    'Generic value: 10',
    'Generic value: 20',
    'Generic value: Hello World',
    'Generic value: GoodBye, Swastik College!',
  ],
  17: [
    'Sum:(15,18)',
    'Difference:(5,12)',
    'Product:(50,45)',
    'Quotient:(2,5)',
    'Modulus:(2,3)',
  ],
  18: [
    'unary + :5',
    'Unary -! : -5',
    'Unary ! : False',
    'Unary ++ : 6',
    'Unary --: 5',
  ],
  19: ['False', 'True', 'False', 'False', 'True', 'False'],
};
